modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/theomenden/Wandering_Cocoa/issues"
license = "MIT"

[[mods]]
modId = "wanderingcocoa"
version = "${file.jarVersion}"
displayName = "Wandering Cocoa"
authors = "Alu"
description = '''
A small mod for adding cocoa to the Wandering Trader's list of trades
'''
logoFile = "icon.png"

[[dependencies.wanderingcocoa]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wanderingcocoa]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wanderingcocoa]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wanderingcocoa]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "wanderingcocoa.mixins.json"
