name: main.yml
on:
  workflow_dispatch:
      inputs:
        mc_version:
          description: 'Minecraft Version'
          required: true
          type: 'string'
          default: '1.21.1'
        mod_version:
          description: 'Mod Version'
          required: true
          type: 'string'
          default: '1.1.05'
        version_type:
          description: 'Version Type'
          required: true
          type: 'choice'
          options:
            - 'alpha'
            - 'beta'
            - 'release'
          default: 'release'
env:
  JAVA_VERSION: 21
  VERSION_TITLE: "${{inputs.mc_version}}+${{inputs.mod_version}}-${{inputs.version_type}}"

jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Cache
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ hashFiles('./gradle.properties') }}-${{ hashFiles('./libs.versions.toml') }}
          restore-keys: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean neoforge:build fabric:build

      - name: Capture Fabric Build Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Fabric Artifacts
          path: fabric/build/libs/

      - name: Capture NeoForge Build Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: NeoForge Artifacts
          path: neoforge/build/libs/

      - name: Upload artifacts to Modrinth/CurseForge for NeoForge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          name: "NeoForge ${{ENV.VERSION_TITLE}}"
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: |
            neoforge/build/libs/!(*-@(dev|sources|all|javadoc|shadow)).jar
            neoforge/build/libs/*-@(dev|sources|javadoc).jar
          modrinth-id: n6THt0cM
          curseforge-id: 1096906
          modrinth-featured: false
          version-type: ${{ inputs.version_type }}
          version: "neoforge-${{inputs.mod_version}}"
          loaders: neoforge
          game-versions: |
            >=1.21.1
      - name: Upload artifacts to Modrinth/CurseForge for Fabric
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          name: "Fabric ${{ENV.VERSION_TITLE}}"
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: |
            fabric/build/libs/!(*-@(dev|sources|all|javadoc|shadow)).jar
            fabric/build/libs/*-@(dev|sources|javadoc).jar
          modrinth-id: n6THt0cM
          curseforge-id: 1096906
          modrinth-featured: false
          version-type: ${{ inputs.version_type }}
          version: "fabric-${{inputs.mod_version}}"
          loaders: fabric
          game-versions: |
            >=1.21.1
      - name: Upload artifacts to GitHub
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          name: "Complete ${{ENV.VERSION_TITLE}}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            fabric/build/libs/!(*-@(dev|sources|all|javadoc|shadow)).jar
            neoforge/build/libs/!(*-@(dev|sources|all|javadoc|shadow)).jar
            fabric/build/libs/*-@(dev|sources|javadoc).jar
            neoforge/build/libs/*-@(dev|sources|javadoc).jar
  close_issues:
    runs-on: ubuntu-latest
    needs: gradle
    permissions:
      contents: write
      issues: write
      deployments: write
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9.1.0
        with:
    # Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    # The message to post on the issue when closing it. If none provided, will not comment when closing an issue.
          close-issue-message: completed #"Closed by ${{ github.repository_owner }} via ${{ github.workflow }} with id: ${{ github.run_id }}"
    # The message to post on the pull request when closing it. If none provided, will not comment when closing a pull requests.
          close-pr-message: completed #"Closed by ${{ github.repository_owner }} via ${{ github.workflow }} with id: ${{ github.run_id }}"
    # The reason to use when closing an issue.
          close-issue-reason: completed #"Closed as a result of ${{ github.workflow }} with id: ${{ github.run_id }}"
          exempt-issue-labels: "renovate"
